version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "8000:8000"
