version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspace
    stdin_open: true # Keep console open
    tty: true # Keep shell prompt open
    ports:
      - "8000:8000"
    working_dir: /workspace  # 追加

  devcontainer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    stdin_open: true # Keep console open
    tty: true # Keep shell prompt open
    environment:
      - PYTHONUNBUFFERED=1
      - UV_PREVIEW=1
    volumes:
      - ..:/workspace
