version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    stdin_open: true # Keep console open
    tty: true # Keep shell prompt open
    environment:
      - PYTHONUNBUFFERED=1
      - UV_PREVIEW=1
    volumes:
      - ..:/workspace
