name: Run Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and run backend container
        run: docker-compose -f ./docker/docker-compose.yaml up --build -d backend

      - name: Run backend tests
        run: docker-compose -f ./docker/docker-compose.yaml exec backend pytest
        working-directory: ./backend

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.7.0'

      - name: Set npm version
        run: npm install -g npm@10.9.2

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run frontend tests
        run: npm test
        working-directory: ./frontend
