name: Run Tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and run test container
        run: docker-compose -f ./docker/docker-compose.yaml up --build -d test

      - name: Run frontend tests
        run: docker compose -f docker/docker-compose.yaml exec test cd frontend && npm run test

      - name: Run backend tests
        run: docker compose -f docker/docker-compose.yaml exec test uv run pytest
        